title: Shrine of Blog
description: Shrine of Blog (sometimes of mess)
theme: just-the-docs

url: https://shrine-blog.github.io

aux_links:
    Template Repository: https://github.com/just-the-docs/just-the-docs-template


collections:
    mess:
        permalink: "/:collection/:path/"
        output: true

just_the_docs:
    collections:
        mess:
            name: Mess